[package]
name = "basics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
bevy = "0.8.0"
bevy_rapier2d = "0.16.0"
bevy-inspector-egui = "0.12.0"